title: Octaloop
description: Outsourced sales and marketing for tech conference organizers
baseurl: "/octaloop"
url: "https://av535.github.io"

exclude:
  - "*.py"
  - "*.pdf"
  - "*.gif"
  - hts-cache
  - hts-log.txt
  - cookies.txt
  - Gemfile
  - Gemfile.lock
  - wrangler.jsonc
  - _archived_posts
